- hosts: localhost
  connection: local
  vars:
    dock_tmpl: <dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/%s.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>
  tasks:
    - name: install casks
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - docker
        - gitup
        - google-chrome
        - google-cloud-sdk
        - google-japanese-ime
        - imageoptim
        - iterm2
        - java
        - karabiner-elements
        - marp
        - slack
        - station
        - visual-studio-code
    # This runs every time, so comment out
    # - name: pin icons to Dock
    #   osx_defaults:
    #     domain: com.apple.dock
    #     key: persistent-apps
    #     type: array
    #     value:
    #       - "{{ dock_tmpl | format('Google Chrome') }}"
    #       - "{{ dock_tmpl | format('Station') }}"
    #       - "{{ dock_tmpl | format('Visual Studio Code') }}"
    #       - "{{ dock_tmpl | format('iTerm') }}"
    #   notify: restart Dock
    - name: Dock settings
      osx_defaults:
        domain: com.apple.dock
        key: "{{ item.key }}"
        type: "{{ item.value.type }}"
        value: "{{ item.value.val }}"
      with_dict:
        minimize-to-application:  {val: true, type: bool}
        orientation:              {val: left, type: string}
        tilesize:                 {val: 55, type: float}
      notify: restart Dock
    - name: Finder settings
      osx_defaults:
        domain: com.apple.finder
        key: "{{ item.key }}"
        type: "{{ item.value.type }}"
        value: "{{ item.value.val }}"
      with_dict:
        FXPreferredViewStyle: {val: clmv, type: string} # Make column view as default
      notify: restart Finder
    - name: Menu bar clock settings
      osx_defaults:
        domain: com.apple.menuextra.clock
        key: "{{ item.key }}"
        type: "{{ item.value.type }}"
        value: "{{ item.value.val }}"
      with_dict:
        DateFormat:           {val: 'M\u6708d\u65e5(EEE)  H:mm', type: string}
        FlashDateSeparators:  {val: false, type: bool}
        IsAnalog:             {val: false, type: bool}
      notify: restart menu bar
    - name: Menu bar battery settings
      osx_defaults:
        domain: com.apple.menuextra.battery
        key: "{{ item.key }}"
        type: "{{ item.value.type }}"
        value: "{{ item.value.val }}"
      with_dict:
        ShowPercent: {val: 'YES', type: string}
      notify: restart menu bar
    - name: Global system settings
      osx_defaults:
        key: "{{ item.key }}"
        type: "{{ item.value.type }}"
        value: "{{ item.value.val }}"
      with_dict:
        AppleShowScrollBars:                  {val: Always, type: string}
        AppleEnableSwipeNavigateWithScrolls:  {val: false, type: bool}
        AppleScrollerPagingBehavior:          {val: 1, type: int}
        # AppleFirstWeekday:                    {val: <dict><key>gregorian</key><int>2</int></dict>, type: string} # Currently cannot set dict
        NSQuitAlwaysKeepsWindows:             {val: true, type: bool}
        com.apple.trackpad.forceClick:        {val: true, type: bool}
        KeyRepeat:                            {val: 2, type: int}
        InitialKeyRepeat:                     {val: 15, type: int}
        AppleKeyboardUIMode:                  {val: 2, type: int}
        AppleShowAllExtensions:               {val: 1, type: int}
    - name: install brews
      homebrew:
        name:
          - awscli
          - bash-git-prompt
          - bat
          - container-diff
          - coreutils
          - diff-so-fancy
          - exa
          - findutils
          - fish
          - fzf
          - gcc
          - ghq
          - gnu-sed
          - gnu-tar
          - gnu-time
          - gradle
          - grep
          - gzip
          - hub
          - jid
          - jq
          - kubernetes-helm
          - micro
          - openssl
          - pipenv
          - readline
          - rustup-init
          - terraform
          - tmux
          - vegeta
    - name: prepare dirs under home
      file:
        path: "~/{{ item }}"
        state: directory
      with_items:
        - src
        - bin
    - name: git-based installations
      git:
        repo: "https://github.com/{{ item.key }}"
        dest: "{{ item.value }}"
      with_dict:
        riywo/anyenv: ~/.anyenv
        znz/anyenv-update: ~/.anyenv/plugins/anyenv-update
        tmux-plugins/tpm: ~/.tmux/plugins/tpm
        # tmshn/dotfiles: ~/src/github.com/tmshn/dotfiles # GHQ-style
    - name: make fish shell valid
      lineinfile:
        dest: /etc/shells
        line: /usr/local/bin/fish
      become: true
    - name: change login shell to fish
      user:
        name: tmshn
        shell: /usr/local/bin/fish
      become: true
  handlers:
    - name: restart Dock
      command: killall Dock
    - name: restart Finder
      command: killall Finder
    - name: restart menu bar
      command: killall SystemUIServer
